---
collections:
  - name: community.general
  - name: awx.awx
  - name: azure.azcollection
    version: ">=2.1.0"
  - name: amazon.aws
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
  - name: kubevirt.core
  - name: f5networks.f5_bigip
  - name: f5networks.f5os
  - name: f5networks.next
  - name: microsoft.ad
  - name: microsoft.sql
  - name: cisco.aci
  - name: cisco.asa
  - name: cisco.catalystwan
  - name: cisco.cdo
  - name: cisco.cml
  - name: cisco.csdac
  - name: cisco.dcnm
  - name: cisco.dnac
  - name: cisco.fmcansible
  - name: cisco.intersight
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.ise
  - name: cisco.meraki
  - name: cisco.mso
  - name: cisco.nac_dc_vlan
  - name: cisco.nae
  - name: cisco.nd
  - name: cisco.nso
  - name: cisco.nxos
  - name: cisco.sdwan
  - name: cisco.sdwan_deployment
  - name: cisco.secure_workload
  - name: cisco.ucs
  - name: vmware.vmware_rest
  - name: cloud.terraform
  - name: azure.azcollection
  - name: amazon.aws
  - name: community.aws
  - name: kubernetes.core
  - name: community.vagrant
  - name: community.crypto
  - name: community.postgresql
  - name: community.dns
  - name: netbox.netbox
  - name: community.docker
  - name: purestorage.flasharray
  - name: purestorage.flashblade
  - name: community.zabbix
  - name: containers.podman
  - name: dellemc.enterprise_sonic
  - name: dellemc.openmanage
  - name: dellemc.os10
  - name: dellemc.os6
  - name: dellemc.os9
  - name: chocolatey.chocolatey
