---
collections:
  - name: amazon.aws
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: awx.awx
  - name: azure.azcollection
  - name: chocolatey.chocolatey
  - name: cisco.ucs
  - name: cloud.terraform
  - name: community.aws
  - name: community.azure
  - name: community.crypto
  - name: community.dns
  - name: community.docker
  - name: community.hashi_vault
  - name: community.kubernetes
  - name: community.kubevirt
  - name: community.vagrant
  - name: community.vmware
  - name: community.windows
  - name: containers.podman
  - name: crowdstrike.falcon
  - name: dellemc.enterprise_sonic
  - name: dellemc.openmanage
  - name: dellemc.os10
  - name: dellemc.os6
  - name: dellemc.os9
  - name: dynatrace.oneagent_deploy
  - name: f5networks.f5_bigip
  - name: f5networks.f5os
  - name: f5networks.next
  - name: f5networks.f5_modules
  - name: kubernetes.core
  - name: kubevirt.core
  - name: microsoft.ad
  - name: microsoft.sql
  - name: netbox.netbox
  - name: openstack.cloud
  - name: ovirt.ovirt
  - name: purestorage.flasharray
  - name: purestorage.flashblade
  - name: purestorage.pure1
  - name: redhatinsights.insights
  - name: theforeman.foreman
  - name: veeamhub.veeam
  - name: vmware.vmware_rest
